name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.20]
        platform: [linux/arm64, linux/amd64]
        os: [ubuntu-latest]
        include:
          - platform: linux/arm64
            goarch: arm64
          - platform: linux/amd64
            goarch: amd64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: |
        GOOS=${{ matrix.os }} GOARCH=${{ matrix.goarch }} go build -v -o ./bin/go-${{ matrix.platform }} ./...
        zip -r ./bin/go-${{ matrix.platform }}.zip ./bin/go-${{ matrix.platform }}
    - name: Test
      run: go test -v ./...
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: go-${{ matrix.platform }}
        path: ./bin/go-${{ matrix.platform }}.zip
